services:
  omekas:
    image: giocomai/omeka-s-docker:v4.2.1
    depends_on:
      - omekas_db
    ports:
      - "8000:80"
    restart: unless-stopped
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: omekas_db
      APPLICATION_ENV: production
      OMEKA_ADMIN_EMAIL: ${OMEKA_ADMIN_EMAIL}
      OMEKA_ADMIN_NAME: "Site Administrator"
      OMEKA_ADMIN_PASSWORD: ${OMEKA_ADMIN_PASSWORD}
      OMEKA_SITE_TITLE: "DH Web Publish"
      OMEKA_TIMEZONE: Asia/Seoul
      OMEKA_LOCALE: ko
    volumes:
      - omekas:/var/www/html/volume

  omekas_db:
    image: mysql:8.4
    restart: unless-stopped
    volumes:
      - omekas_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  omekas:
  omekas_db:
